// See https://aka.ms/new-console-template for more information

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using ApplicationConsole;



// Afficher tous les noms de municipalite dans la console 
MunicipalitesClient client = new MunicipalitesClient();

Task<ICollection<MunicipaliteModel>> municipalites = client.GetAllAsync();
municipalites.Wait();

foreach (var municipalite in municipalites.Result)
{
    Console.WriteLine(municipalite.NomMunicipalite);
}


// Modifier la municipalite de Québec
MunicipaliteModel villeAModifier = new MunicipaliteModel();
villeAModifier.NomMunicipalite = "Quebecq";
villeAModifier.MunicipaliteId = 23027;
villeAModifier.AdresseCourriel = "311@ville.quebec.qc.ca";
villeAModifier.AdresseWeb = "www.ville.quebec.qc.ca";
villeAModifier.DateProchaineElection = new DateTime(2025, 11, 02);
villeAModifier.Actif = true;

client.PutAsync(23027, villeAModifier);



